services:
  auth_service:
    build: ./services/auth_service
    ports:
      - "8001:8000"
    depends_on:
      - auth_db
    env_file:
      - .env

  auth_db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass