services:
  auth_service:
    build: ./services/auth_service
    ports:
      - "8001:8000"
    depends_on:
      - auth_db
    env_file:
      - .env

  auth_db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}